# Generated by Django 4.2.4 on 2023-09-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_end_data_alter_question_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
