# Generated by Django 4.2.5 on 2023-09-16 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 16, 14, 6, 41, 442460, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
